version: '3'
services:
  bd:
    container_name: bd
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: vaXKRzqk.4
      POSTGRES_DB: fte_portal
    volumes:
      - ./volumes/database:/var/lib/postgresql/data
  
  backend:
    container_name: backend
    build: ./backend
    depends_on:
      - bd
    ports:
      - 1337:1337
  
  frontend:
    container_name: frontend
    build: ./frontend
    depends_on:
      - backend
    ports:
      - 3000:80